services:
  db:
    image: postgres:15-alpine
    container_name: shop_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: shop_redis
    restart: always
    ports:
      - "6381:6379"

  api:
    build: ./backend
    image: shop_api
    container_name: shop_api
    restart: always
    command: python app.py
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
    depends_on:
      - db
      - redis

  celery:
    build: ./backend
    image: shop_celery
    container_name: celery
    restart: always
    command: celery -A app:celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - API_HOST=${API_HOST}
      - API_SCHEME=${API_SCHEME}
    depends_on:
      - db
      - redis

  flower:
    image: mher/flower
    container_name: celery_flower
    restart: always
    command: celery --broker=${REDIS_URL} flower --port=${FLOWER_PORT}
    environment:
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
      - FLOWER_PORT=${FLOWER_PORT}
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    depends_on:
      - redis
      - celery

  locust:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: shop_locust
    pull_policy: never
    container_name: shop_locust
    restart: "no"
    command: locust -f locustfile.py --host=http://api:5000
    volumes:
      - ./backend:/app
    ports:
      - "8089:8089"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - api

volumes:
  postgres_data:
