FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV FLASK_ENV=testing

WORKDIR /app

# Install all dependencies 
COPY backend/requirements-dev.txt ./requirements-dev.txt
COPY backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements-dev.txt

# Copy the backend source code and tests
COPY backend/ .


ENV PYTHONPATH=/app

CMD ["pytest", "tests/", "-v", "--junitxml=test-results.xml", "-x"]
